### ISSUE TITLE
Wifi channel changing does not work on the web interface

### ISSUE THREAD

**Issue by Kloadut** [labriqueinternet/hotspot_ynh#17]
**Step to reproduce**:
* Go to the Hotspot web interface
* Click on the channel (6 by default)
* Select another channel

**Current behaviour**:
* The channel is not selected

**Expected behaviour**:
* The channel is properly selected and changes when clicking on "Save and reload"

**Comment by jvaubourg** [comment]
I tried with the last version of Hotspot and I didn't met this problem :/.

The channel was 6 by default, I selected 8 and I saved. After the reload of the web page, the channel 8 was selected. And my SSID was correctly announced on the channel 8. I tried with Firefox and Chromium.

Could you confirm your bug?

After changing the channel, what do you see with:
```
yunohost app setting hotspot wifi_channel
```

**Comment by jvaubourg** [comment]
Did you retried your bug?
