### ISSUE TITLE
(re)install fails if dependencies are not installed

### ISSUE THREAD

**Issue by JocelynDelalande** [labriqueinternet/hotspot_ynh#23]
Hi,

- I did a first install, it worked (though iw, hostapd and sipcalc were installed prior to the app install)
- It just worked
- I removed the app
- I apt-get remove sipcalc hostapd iw
- I try to re-install the app, it fails with « hotspot is not installed » error on web interface and no error in logs
- From that point, even if I apt-get install sipcalc hostapd iw, install will never succeed

I think it's easily reproducible, someone else face this bug ?

**Comment by jvaubourg** [comment]
I'm not able to reproduce this bug, and I don't understand how you can obtain a message "hotspot is not installed" on the web interface :/.

You say you have no error during the second installation, just an error on the web interface ? Could do confirm your bug?

**Comment by JocelynDelalande** [comment]
Can't reproduce anymore with latest version of `hotspot_ynh` (even tested on fresh brique install) :) I was doing it with the ATH9271 dongle (the free one), so maybe, my bug was related to #24 

So… happily closing :)
