### ISSUE TITLE
Installation fails with the free antenna

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/hotspot_ynh#24]
We have a big issue with the free wifi antenna: the installation fails because no wifi interface is detected.

Hotspot installs the correct firmwares, but the USB dongle has to be unplug and replug... And because YunoHost is not able to correctly handle the installation errors, Hotspot is a in unstable state and cannot be removed or reinstalled after the fail.

This huge bug was found by @opi .

**Comment by JocelynDelalande** [comment]
I can confirm it works, thanks @jvaubourg

**Comment by opi** [comment]
Thanks for the fix !

**Comment by jvaubourg** [comment]
Some more explanations for @bleuchtang ...

I didn't find a way to unplug/replug the USB dongle by software. I think there is no real solution for that, because even Debian firmware packets have no solution for that (e.g. firmware-atheros, the non-free firmware for the free antenna, does not up the wlan0 interface after the installation and we need to replug the USB dongle or reboot the system).

For now, with this commit, Hotspot does not fail if there is no wifi interface found during the installation. There is just a warning at the end of the installation and the service is disabled by default. When the user goes to the web admin, he sees a warning notifying him that he has to select a wifi interface. The warning also advises the user to unplug/replug its USB dongle in the case he uses one and if he does not see the corresponding wifi interface. Then, he just has to reload the page by clicking a link in the warning message, select the new wifi interface and enable the service.
