### ISSUE TITLE
Warnings when installing from Web interface

### ISSUE THREAD

**Issue by keomabrun** [labriqueinternet/hotspot_ynh#38]
The following appears on the top bar when installing the app from the web interface.
```
dpkg-preconfigure: unable to re-open stdin:
debconf: falling back to frontend: Teletype
debconf: (This frontend requires a controlling tty.)
debconf: unable to initialize frontend: Readline
debconf: falling back to frontend: Readline
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: unable to initialize frontend: Dialog
E: Could not open file /var/lib/apt/lists/httpredir.debian.org_debian_dists_stretch-backports_main_Contents-armhf.diff_Index - open (2: No such file or directory)
```

**Comment by alexAubin** [comment]
The first lines are not so much worrying, but the last one uh, why are backports in there ?

**Comment by keomabrun** [comment]
I am using the lastest Yunohost LIME2 image from build.yunohost.org
It looks like backports are enable on this image:
From `/etc/apt/source.list`:
```
deb http://httpredir.debian.org/debian stretch-backports main contrib non-free
```
Armbian ?

**Comment by alexAubin** [comment]
what the actual fuck :|

**Comment by alexAubin** [comment]
Should be fixed by : https://github.com/YunoHost/arm-images/commit/9b6dc48660c0781ca4f5524b3277b649d8f3f2cd for future builds :/

**Comment by alexAubin** [comment]
Made another PR about the annoying warnings because I see those a lot recently since I'm back to doing stuff from the webadmin :P 

https://github.com/YunoHost/yunohost/pull/643

**Comment by alexAubin** [comment]
Closing because that should be fixed now (in unstable, so will be effective once it gets released)
