### ISSUE TITLE
use `systemctl is-enabled` instead of app variable

### ISSUE THREAD

**Issue by keomabrun** [labriqueinternet/hotspot_ynh#42]
Currently the status (enabled/disabled) of the ynh-hotspot service is managed as an app variable. I believe it should be using `systemctl is-enabled` instead.

**Comment by keomabrun** [comment]
The only (potentially harmful) drawback I see is that the web interface would have to have access to `systemctl`. 

Any suggestions ?

**Comment by alexAubin** [comment]
Eh, not sure to understand why that's a drawback ? The user already has sudo-access so ? :D

**Comment by keomabrun** [comment]
It does. And it should not :cry:
