### ISSUE TITLE
Moulinette Lock Error

### ISSUE THREAD

**Issue by keomabrun** [labriqueinternet/hotspot_ynh#47]
https://paste.yunohost.org/raw/ovubiqenuv

The error occurs when we try to disable the service (if no device is detected).

**Comment by alexAubin** [comment]
Hmyea by the way, we should try to get rid of those `ynh_systemctl` at some point ... This was an ugly hackish solution from 1.5 year ago.

Instead, the --need_lock was introduced to cover this use case : https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/actionsmap/yunohost.yml#L1146

So basically : 
- beware that this is only available in 3.x (not sure which version exactly but, *not jessie*). c.f. the fact that the manifest still requires yunohost 2.2 :sweat_smile: 
- when creating the service with `yunohost service add`, `--need_lock` should be added
- then to enable, start, ... the service, `yunohost service [enable|start|...]` should be used (*not* systemctl directly)
