### ISSUE TITLE
Compliance with systemd

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/hotspot_ynh#6]
The first release of the Internet Cube should use Debian Jessie. Because we use a sysvinit service, we need to convert it to the systemd format and replace all the "service" commands by "systemctl". Status commands must be replaced by the is-active option.

**Comment by jvaubourg** [comment]
Should be okay from e15fb76389c4cfba800d9320dc1446be41c13bae.

We need strong tests before merging (and losing wheezy compatibility).

**Comment by sbadia** [comment]
fixed by #15
